server:
  ## HTTP Server port
  port: 8080
  compression:
    ## Enable response compression
    enabled: true
    ## The comma-separated list of mime types that should be compressed
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    ## Compress the response only if the response size is at least 1KB
    min-response-size: 1024

## Config Application and Database
spring:
  application:
    name: abrigo-animal
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    jmx:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/abrigo_animal?ApplicationName=${spring.application.name}
    username: teste
    password: teste
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
